/* Section 5 — Balance Sheet */
(function () {
  'use strict';
  const row = (a, b) => `<tr><td class="lbl"><b>${a}</b></td><td class="lbl wrap">${b}</td></tr>`;
  SAT.section({
    id: 'balance', num: 6, title: 'Balance Sheet',
    intro: 'A snapshot at one date of what the company <b>owns</b>, what it <b>owes</b>, and what is left for <b>shareholders</b>.',
    he: 'מאזן: נכסים = התחייבויות + הון עצמי.',
    top: `<div class="card bs-eq">
      <div class="bs-col a"><div class="bs-h"><a href="#balance/assets">ASSETS</a></div><div class="bs-b">What the company owns<br><small>Cash · Receivables · Inventory · PP&amp;E · Intangibles</small></div></div>
      <div class="bs-op">=</div>
      <div class="bs-col"><div class="bs-stack"><div class="bs-col l"><div class="bs-h"><a href="#balance/liabilities">LIABILITIES</a></div><div class="bs-b">What it owes<br><small>Payables · Debt · Deferred revenue</small></div></div>
      <div class="bs-plus">+</div>
      <div class="bs-col e"><div class="bs-h"><a href="#balance/equity">SHAREHOLDERS’ EQUITY</a></div><div class="bs-b">What belongs to owners<br><small>= Assets − Liabilities</small></div></div></div></div>
    </div>`,
  });
  SAT.concepts('balance', [
    { id: 'assets', title: 'Assets', short: 'Resources the company owns/controls that provide future benefit.', stmt: 'bs',
      what: 'Everything the company owns or controls that is expected to bring future economic benefit. Split into <b>current</b> (turn into cash within ~1 year) and <b>long-term</b>.',
      formula: 'Assets = Liabilities + Shareholders’ Equity',
      body: `<table class="t"><tbody>${row('Current Assets', 'Cash, accounts receivable, inventory, short-term investments')}${row('Long-Term Assets', 'PP&amp;E, goodwill &amp; intangibles, long-term investments, lease assets')}</tbody></table>`,
      better: ['na'], compare: ['Asset growth vs revenue growth (asset efficiency)'],
      watch: 'Assets are mostly recorded at historical cost, not current value. Goodwill can be large and later written down.',
      where: 'Top half (or left side) of the Balance Sheet.', related: ['current-assets', 'ppe', 'liabilities'] },
    { id: 'current-assets', title: 'Current Assets', short: 'Assets expected to turn into cash within a year.', stmt: 'bs',
      what: 'Assets that will be converted to cash or used up within about one year: cash, receivables, inventory, prepaid expenses, short-term investments.',
      better: ['context'], compare: ['Current liabilities (current ratio)'],
      watch: 'Not all current assets are equally liquid — obsolete inventory or doubtful receivables may never become cash.',
      where: 'Balance Sheet, “Total current assets”.', related: ['current-ratio', 'cash', 'receivables', 'inventory'] },
    { id: 'cash', title: 'Cash & Cash Equivalents', aka: ['Cash', 'Cash and short-term investments'], short: 'Money in the bank plus very liquid short-term investments.', stmt: 'bs', key: 1,
      what: 'Money in the bank and very liquid, low-risk investments (Treasury bills, money-market funds). Many analysts add short-term investments too.',
      interp: '<b>Why it matters:</b> stability — cash lets a company survive downturns and invest when others can’t. Valuation — cash belongs to shareholders, so it is <b>subtracted</b> in Enterprise Value and <b>added</b> back in the DCF equity bridge.',
      better: ['context', 'More is safer, but very large idle cash may earn little.'], compare: ['Debt (net cash / net debt)', 'Annual cash burn or FCF'],
      watch: 'Some cash may be trapped abroad, restricted, or needed for operations (e.g. customer funds held by payment companies).',
      where: 'First line of current assets.', related: ['net-cash', 'enterprise-value', 'equity-value'] },
    { id: 'receivables', title: 'Accounts Receivable', abbr: 'AR', short: 'Money customers owe for things already delivered.', stmt: 'bs',
      what: 'Amounts customers owe for goods/services already delivered but not yet paid for.',
      example: [['Sales on 60-day terms', '$10'], ['Paid so far', '$6'], ['Receivable', '$4', 'res']],
      interp: 'Receivables growing much faster than revenue may signal looser credit terms, collection problems, or aggressive revenue recognition.',
      better: ['context', 'Lower relative to revenue = faster collection.'], compare: ['Revenue growth', 'Days Sales Outstanding (AR / Revenue × 365)'],
      watch: 'Rising receivables make profit look better than cash.', where: 'Current assets.', related: ['profit-vs-cash', 'working-capital'] },
    { id: 'inventory', title: 'Inventory', short: 'Goods held for sale, in production, or raw materials.', stmt: 'bs',
      what: 'Raw materials, work-in-progress and finished goods not yet sold.',
      interp: 'Inventory ties up cash. Rising faster than sales can foreshadow discounts and write-downs.',
      better: ['context', 'Lower relative to sales = more efficient.'], compare: ['Sales growth', 'Inventory turnover (COGS / Inventory)'],
      watch: 'Obsolete or fashion-sensitive inventory may be worth far less than its book value.', where: 'Current assets.', related: ['working-capital', 'current-ratio'] },
    { id: 'ppe', title: 'PP&E', abbr: 'Property, Plant & Equipment', short: 'Long-term physical assets: buildings, factories, machines, servers.', stmt: 'bs',
      what: 'Physical long-term assets used to operate the business, shown net of accumulated depreciation.',
      interp: 'CapEx increases PP&amp;E; depreciation reduces it. Capital-intensive businesses have large PP&amp;E relative to revenue.',
      better: ['na'], compare: ['Revenue / PP&E (asset turnover)', 'Peers'],
      watch: 'Recorded at historical cost less depreciation — may differ greatly from replacement or market value.', where: 'Long-term assets.', related: ['capex', 'invested-capital'] },
    { id: 'liabilities', title: 'Liabilities', short: 'What the company owes to others.', stmt: 'bs',
      what: 'Obligations the company owes: suppliers, lenders, employees, tax authorities, customers who prepaid. Split into <b>current</b> (due within ~1 year) and <b>long-term</b>.',
      body: `<table class="t"><tbody>${row('Current Liabilities', 'Accounts payable, short-term debt, accrued expenses, deferred revenue')}${row('Long-Term Liabilities', 'Long-term debt, lease liabilities, pensions, deferred taxes')}</tbody></table>`,
      better: ['context'], compare: ['Assets', 'Equity', 'Cash flow'],
      watch: 'Not all liabilities are bad: deferred revenue is cash customers already paid.', where: 'Bottom half of the Balance Sheet.', related: ['current-liabilities', 'debt', 'equity'] },
    { id: 'current-liabilities', title: 'Current Liabilities', short: 'Obligations due within a year.', stmt: 'bs',
      what: 'Obligations due within about a year: accounts payable, short-term debt and current portion of long-term debt, accrued expenses, deferred revenue.',
      better: ['context'], compare: ['Current assets (current ratio)'],
      watch: 'Large debt maturities inside current liabilities can be a refinancing risk.', where: 'Balance Sheet, “Total current liabilities”.', related: ['current-ratio', 'payables'] },
    { id: 'payables', title: 'Accounts Payable', abbr: 'AP', short: 'Money the company owes its suppliers.', stmt: 'bs',
      what: 'Bills from suppliers the company has received but not yet paid.',
      interp: 'Paying suppliers later keeps cash longer — a free source of financing for companies with bargaining power.',
      better: ['context'], compare: ['COGS (Days Payable Outstanding)', 'Previous years'],
      watch: 'Stretching payables can boost cash flow temporarily — it can’t continue forever.', where: 'Current liabilities.', related: ['working-capital', 'profit-vs-cash'] },
    { id: 'debt', title: 'Debt', aka: ['Borrowings', 'Short-Term Debt', 'Long-Term Debt'], short: 'Money borrowed that must be repaid with interest.', stmt: 'bs', key: 1, tags: ['short-term debt', 'long-term debt', 'bonds', 'loans'],
      what: 'Borrowed money (bank loans, bonds) that must be repaid with interest.<br><b>Short-Term Debt</b> — due within a year (including the current portion of long-term debt).<br><b>Long-Term Debt</b> — due after more than a year.',
      interp: '<b>Interest burden:</b> interest payments reduce profit and cash. <b>Maturity risk:</b> debt must be repaid or refinanced when due — dangerous if it comes due when credit markets are closed or the business is weak.',
      better: ['lower', 'Less debt = more resilience (though some cheap debt can be efficient).'], compare: ['Cash (net debt)', 'EBITDA (Debt/EBITDA)', 'Maturity schedule'],
      watch: 'Leases and other obligations behave like debt but may not be included in “debt” on data sites.',
      where: 'Current and long-term liabilities; debt maturity note in the 10-K.', related: ['net-debt', 'debt-ebitda', 'enterprise-value'] },
    { id: 'net-cash', title: 'Net Cash', short: 'Cash − Debt (when positive).', stmt: 'calc',
      what: 'Cash minus total debt. If positive, the company has more cash than debt.',
      formula: 'Net Cash = Cash − Debt',
      example: [['Cash', '$8B'], ['Debt', '$5B'], ['Net Cash', '$3B', 'res']],
      interp: 'Positive net cash means the company could repay all its debt today and still have cash left — financial flexibility for downturns, buybacks or acquisitions.',
      better: ['higher'], compare: ['Market Cap (what % of the value is cash?)', 'Annual cash burn'],
      watch: 'Some cash may be needed to run the business or be trapped abroad.', where: 'Calculated from the Balance Sheet.',
      calc: { id: 'h-nc', defaults: { cash: '8B', debt: '5B' }, fields: [{ k: 'cash', label: 'Cash' }, { k: 'debt', label: 'Debt' }], outputs: [{ id: 'n', label: 'Net Cash / (Net Debt)', f: (v) => v.cash - v.debt, tone: (x) => SAT.tone(x) }] },
      related: ['net-debt', 'cash', 'debt'] },
    { id: 'net-debt', title: 'Net Debt', short: 'Debt − Cash (when debt exceeds cash).', stmt: 'calc', key: 1,
      what: 'Total debt minus cash. Used when debt exceeds cash.',
      formula: 'Net Debt = Debt − Cash',
      example: [['Debt', '$10B'], ['Cash', '$2B'], ['Net Debt', '$8B', 'res']],
      interp: 'Analysts care more about net debt than gross debt because cash could be used to repay debt. Two companies each with $10B of debt are very different if one has $9B of cash.',
      better: ['lower'], compare: ['EBITDA (Net Debt/EBITDA)', 'FCF (years to repay)'],
      watch: 'Assumes all cash is available to repay debt, which may not be true.', where: 'Calculated from the Balance Sheet.', related: ['net-cash', 'debt-ebitda', 'enterprise-value'] },
    { id: 'current-ratio', title: 'Current Ratio', short: 'Current Assets / Current Liabilities — short-term liquidity.', stmt: 'calc', key: 1,
      what: 'Measures whether short-term assets cover short-term obligations.',
      formula: 'Current Ratio = Current Assets / Current Liabilities',
      example: [['Current Assets', '$12B'], ['Current Liabilities', '$6B'], ['Current Ratio', '2.0', 'res']],
      interp: '2.0 means $2 of current assets for every $1 of current liabilities.',
      better: ['context', 'Higher = more liquid, but too high can mean idle capital.'], compare: ['History', 'Industry peers'],
      watch: '<b>Limitations:</b> inventory may not be sellable; receivables may not be collected; subscription companies often run below 1.0 safely because of deferred revenue; it says nothing about long-term debt.',
      where: 'Calculated from the Balance Sheet.',
      q: { tells: 'Short-term liquidity.', hl: 'Higher is safer, up to a point.', compare: 'History and same-industry peers.', fool: 'Illiquid inventory, deferred revenue, timing of the balance-sheet date.' },
      related: ['current-assets', 'current-liabilities', 'working-capital'] },
    { id: 'equity', title: 'Shareholders’ Equity', aka: ['Stockholders’ Equity', 'Book Value', 'Net Assets'], short: 'Assets − Liabilities: the owners’ accounting claim.', stmt: 'bs', key: 1,
      what: 'What would be left for shareholders if all assets were sold at book value and all liabilities paid.',
      formula: 'Shareholders’ Equity = Assets − Liabilities',
      example: [['Assets', '$50B'], ['Liabilities', '$30B'], ['Equity', '$20B', 'res']],
      interp: 'Grows with retained profits and share issuance; shrinks with losses, dividends and buybacks.',
      better: ['context'], compare: ['Market Cap (Price/Book)', 'Previous years'],
      watch: 'Large buybacks can make equity small or even negative in excellent businesses.', where: 'Bottom of the Balance Sheet.', related: ['book-value', 'invested-capital'] },
    { id: 'book-value', title: 'Book Value', aka: ['Book Value per Share'], short: 'Accounting value of equity — not market value.', stmt: 'bs',
      what: 'The accounting value of shareholders’ equity on the balance sheet. Per share: Equity / Shares.',
      formula: 'Book Value = Assets − Liabilities\nPrice / Book = Market Cap / Book Value',
      interp: '<b>Book Value ≠ Market Value.</b> Book value reflects historical accounting; market value reflects expectations about future cash flows. Asset-light businesses (software, brands) trade far above book.',
      better: ['na'], compare: ['Market Cap', 'Peers in asset-heavy industries (banks, insurers)'],
      watch: 'Most useful for banks and asset-heavy firms; nearly meaningless for many tech companies.', where: 'Balance Sheet.', related: ['equity', 'market-cap'] },
    { id: 'ebitda', title: 'EBITDA', abbr: 'Earnings Before Interest, Taxes, Depreciation and Amortization', short: 'Operating Income + D&A. A rough earnings proxy — not cash.', stmt: 'calc', key: 1,
      what: 'Operating profit before deducting depreciation and amortization (and before interest and taxes).',
      he: 'EBITDA — רווח לפני ריבית, מסים, פחת והפחתות. איננו תזרים מזומנים!',
      formula: 'EBITDA ≈ Operating Income + Depreciation & Amortization',
      example: [['Operating Income', '$25'], ['D&A', '$8'], ['EBITDA', '$33', 'res']],
      interp: '<b>Analysts</b> use it to compare businesses with different debt, tax and depreciation policies. <b>Lenders</b> use it to size debt and set covenants (Debt/EBITDA). It is useful for comparing businesses because it is capital-structure neutral.',
      better: ['higher'], compare: ['Operating income and FCF', 'CapEx (how much EBITDA is really consumed?)'],
      watch: '<b>EBITDA ≠ CASH FLOW.</b> It ignores CapEx, working capital, interest and taxes. It can make <b>capital-intensive businesses look much better</b> than they are — depreciation reflects equipment that must be replaced.',
      where: 'Calculated (sometimes reported as “Adjusted EBITDA” — check what’s excluded).',
      q: { tells: 'Rough operating earnings power before capital structure.', hl: 'Higher is better, but it isn’t cash.', compare: 'Operating income, OCF, CapEx.', fool: 'Capital intensity, “adjusted” add-backs (SBC, restructuring every year).' },
      related: ['debt-ebitda', 'ev-ebitda', 'fcf'] },
    { id: 'debt-ebitda', title: 'Debt / EBITDA', short: 'Total Debt / EBITDA — rough leverage in “years of EBITDA”.', stmt: 'calc', key: 1, tags: ['leverage'],
      what: 'A rough measure of leverage: how many years of EBITDA it would take to repay all debt.',
      formula: 'Debt / EBITDA = Total Debt / EBITDA',
      example: [['Debt', '$10B'], ['EBITDA', '$5B'], ['Debt / EBITDA', '2.0x', 'res']],
      interp: 'Conceptually: <b>1x</b> — debt equals one year of EBITDA, light. <b>2x</b> — two years. <b>5x</b> — five years of all EBITDA, heavy for most businesses. There are <b>no universal thresholds</b>: stable utilities carry more debt safely than cyclical or fast-changing businesses.',
      better: ['lower', 'Acceptable levels vary by industry.'], compare: ['Industry peers', 'History', 'Net Debt / EBITDA'],
      watch: 'EBITDA ignores CapEx and can collapse in a downturn, so leverage can rise suddenly.', where: 'Calculated from Balance Sheet + Income Statement.',
      q: { tells: 'How heavy the debt load is relative to earnings power.', hl: 'Lower is generally safer.', compare: 'Peers in the same industry, covenants.', fool: 'Peak-cycle EBITDA, “adjusted” EBITDA, leases excluded.' },
      related: ['debt', 'ebitda', 'net-debt'] },
  ]);
})();
