/* Section 3 — Income Statement, Section 3b — Profitability & Margins */
(function () {
  'use strict';
  const F = SAT.fin;
  const pct = (x) => SAT.tone(x);

  SAT.section({
    id: 'income', num: 3, title: 'Income Statement',
    intro: 'Also called the P&amp;L (Profit &amp; Loss). It shows how revenue flows down to net income over a period — a quarter (10-Q) or a year (10-K).',
    he: 'דוח רווח והפסד: מההכנסות מורידים עלויות שלב אחר שלב עד לרווח הנקי.',
    top: `<div class="card is-struct">
      <div class="is-l">Revenue</div><div class="is-l m">− Cost of Revenue</div><div class="is-line"></div><div class="is-l t"><a href="#income/gross-profit">Gross Profit</a></div>
      <div class="is-l m">− Operating Expenses <span class="muted">(R&amp;D, S&amp;M, G&amp;A)</span></div><div class="is-line"></div><div class="is-l t"><a href="#income/operating-income">Operating Income</a> <span class="muted">(≈ EBIT)</span></div>
      <div class="is-l m">− Interest</div><div class="is-l m">− Other Expenses <span class="muted">(+ other income)</span></div><div class="is-l m">− Taxes</div><div class="is-line"></div><div class="is-l t"><a href="#income/net-income">Net Income</a></div>
    </div>`,
  });
  SAT.concepts('income', [
    { id: 'revenue', title: 'Revenue', aka: ['Sales', 'Turnover', 'Top line'], short: 'Total money from selling products/services, before any expenses.', stmt: 'is', key: 1, tags: ['yoy', 'qoq', 'revenue growth', 'sales growth'],
      what: 'The total amount a company earns from selling its products or services during a period, <b>before any expenses</b> are subtracted. The first line of the income statement — the “top line”.',
      he: 'הכנסות = סך המכירות לפני כל הוצאה.',
      formula: 'Revenue Growth = (Current Revenue − Previous Revenue) / Previous Revenue',
      example: [['Previous year revenue', '$100'], ['Current year revenue', '$120'], ['Revenue growth (YoY)', '20%', 'res']],
      interp: '<b>YoY (Year over Year)</b> compares a period with the same period a year earlier (Q2 2026 vs Q2 2025) — removes seasonality. <b>QoQ (Quarter over Quarter)</b> compares with the immediately preceding quarter (Q2 vs Q1) — shows momentum but is distorted by seasonality.',
      better: ['higher', 'Faster growth is usually better — if it is profitable and not bought at any cost.'],
      compare: ['Previous years (trend, acceleration or deceleration)', 'Competitors’ growth', 'Market / TAM growth'],
      watch: '<b>Revenue ≠ Profit.</b> Growth can be inflated by acquisitions, currency moves, price-only increases, or one-off contracts. High growth with deep losses can destroy value.',
      where: 'First line of the income statement.',
      q: { tells: 'Size of the business and pace of demand.', hl: 'Higher growth usually better — if profitable.', compare: 'History, peers, market growth; organic vs acquired.', fool: 'Acquisitions, currency, easy comparisons after a bad year, aggressive revenue recognition.' },
      calc: { id: 'h-revg', defaults: { prev: '100', cur: '120' }, fields: [{ k: 'prev', label: 'Previous Revenue' }, { k: 'cur', label: 'Current Revenue' }],
        outputs: [{ id: 'g', label: 'Revenue Growth', fmt: 'pct', f: (v) => F.growth(v.cur, v.prev), tone: pct }] },
      related: ['cogs', 'growth-drivers', 'tam'] },
    { id: 'cogs', title: 'Cost of Revenue', abbr: 'COGS — Cost of Goods Sold', aka: ['Cost of Sales', 'COGS', 'COS'], short: 'Direct costs of producing/delivering what was sold.', stmt: 'is',
      what: 'The <b>direct</b> costs associated with generating revenue — costs that rise and fall with each unit sold. “COGS” is used for physical goods; “Cost of Revenue” is the broader term that also covers services.',
      example: [['Manufacturing company', 'Raw materials, factory labour, factory overhead, depreciation of production equipment'], ['Software company', 'Cloud hosting, customer support, third-party licences, payment processing'], ['Retailer', 'Purchase cost of the merchandise sold, inbound freight, shrinkage']],
      interp: 'Revenue − Cost of Revenue = Gross Profit. The lower COGS is relative to revenue, the more each sale contributes to everything else.',
      better: ['lower', 'Lower as a % of revenue (holding quality constant).'], compare: ['COGS % of revenue over time', 'Competitors'],
      watch: 'Companies classify costs differently (e.g. shipping, support), which makes peer comparisons tricky.',
      where: 'Line directly below Revenue.', related: ['gross-profit', 'opex'] },
    { id: 'gross-profit', title: 'Gross Profit', short: 'Revenue − Cost of Revenue.', stmt: 'is',
      what: 'What remains from revenue after paying the direct costs of producing the product or service. It is the pool of money that must pay for R&amp;D, sales, administration, interest, taxes — and profit.',
      formula: 'Gross Profit = Revenue − Cost of Revenue',
      example: [['Revenue', '$100'], ['Cost of Revenue', '$40'], ['Gross Profit', '$60', 'res']],
      interp: 'Gross profit should grow at least as fast as revenue. If it grows slower, direct costs are rising faster than prices.',
      better: ['higher'], compare: ['Growth of gross profit vs growth of revenue', 'Peers'],
      watch: 'A big gross profit does not mean the company is profitable — operating expenses can consume all of it.',
      where: 'Often shown directly; otherwise Revenue − Cost of Revenue.', related: ['gross-margin', 'cogs', 'operating-income'] },
    { id: 'opex', title: 'Operating Expenses', abbr: 'OpEx', aka: ['SG&A + R&D', 'Operating costs'], short: 'R&D + S&M + G&A — costs of running and growing the company.', stmt: 'is', key: 1, tags: ['r&d', 'research', 's&m', 'sales and marketing', 'g&a', 'sg&a'],
      what: 'Costs of running and growing the business that are <b>not directly tied to each unit sold</b>:<br><b>R&amp;D</b> — Research &amp; Development: engineers, new products, technology.<br><b>S&amp;M</b> — Sales &amp; Marketing: salespeople, advertising, commissions, customer acquisition.<br><b>G&amp;A</b> — General &amp; Administrative: executives, finance, legal, HR, offices.<br>(S&amp;M + G&amp;A are often reported together as <b>SG&amp;A</b>.)',
      he: 'הוצאות תפעול: מו"פ, שיווק ומכירות, הנהלה וכלליות.',
      formula: 'Operating Income = Gross Profit − Operating Expenses',
      example: [['Gross Profit', '$60'], ['R&D', '$15'], ['S&M', '$15'], ['G&A', '$5'], ['Operating Expenses', '$35', 'res']],
      interp: '<b>Cost of Revenue vs OpEx:</b> Cost of Revenue scales with each unit sold (direct). OpEx is the cost of the organisation — it can grow slower than revenue, which creates operating leverage.',
      better: ['context', 'Lower as % of revenue is more efficient, but R&D and S&M are also investment in growth.'], compare: ['Each line as % of revenue over time', 'Peers'],
      watch: '<b>DO NOT subtract Cost of Revenue twice.</b> Gross Profit already has Cost of Revenue removed. Some data sites show “Total operating expenses” that <i>includes</i> COGS — check before using it.',
      where: 'Lines between Gross Profit and Operating Income.', related: ['operating-income', 'operating-leverage', 'cogs'] },
    { id: 'operating-income', title: 'Operating Income', aka: ['Operating Profit', 'EBIT (in many contexts)'], short: 'Gross Profit − Operating Expenses: profit from core operations.', stmt: 'is', key: 1, tags: ['ebit'],
      what: 'Profit from the company’s core business after all operating costs, <b>before</b> interest and taxes. It measures how profitable the operations are, regardless of how the company is financed.',
      he: 'רווח תפעולי — הרווח מפעילות הליבה, לפני ריבית ומסים.',
      formula: 'Operating Income = Gross Profit − Operating Expenses',
      example: [['Gross Profit', '$60'], ['Operating Expenses', '$35'], ['Operating Income', '$25', 'res']],
      interp: 'Strictly, <b>EBIT</b> (Earnings Before Interest and Taxes) also includes non-operating income; in practice the two are often used interchangeably.',
      better: ['higher'], compare: ['Previous years', 'Peers (via operating margin)'],
      watch: 'One-off items (restructuring, impairments, legal settlements) can distort it. Check “adjusted” figures against GAAP.',
      where: 'Labelled “Operating income” or “Income from operations”.', related: ['operating-margin', 'nopat', 'ebitda'] },
    { id: 'net-income', title: 'Net Income', aka: ['Net Profit', 'Net Earnings', 'Bottom line'], short: 'Profit left for shareholders after all expenses, interest and taxes.', stmt: 'is', key: 1,
      what: 'What remains after <b>operating expenses</b>, <b>interest</b>, <b>taxes</b>, and <b>other income/expenses</b>. The “bottom line”, attributable to shareholders.',
      he: 'רווח נקי — הרווח החשבונאי שנשאר לבעלי המניות.',
      formula: 'Net Income = Operating Income − Interest ± Other Income/Expenses − Taxes',
      example: [['Operating Income', '$25'], ['Interest', '$3'], ['Taxes', '$5'], ['Net Income', '$17', 'res']],
      interp: 'Net income is <b>accounting profit</b>, not cash. It includes non-cash items (depreciation, stock-based compensation) and timing differences (receivables).',
      better: ['higher'], compare: ['Operating cash flow (cash conversion)', 'Previous years'],
      watch: 'One-off gains (selling a business, investment gains, tax benefits) can inflate it. <b>Profit ≠ Cash Flow.</b>',
      where: 'Last main line of the income statement.', related: ['net-margin', 'eps', 'profit-vs-cash'] },
  ]);

  SAT.section({
    id: 'margins', num: 4, title: 'Profitability & Margins',
    intro: 'Margins turn dollar profits into percentages so you can compare across time and companies. Each margin answers: “of every $100 of revenue, how much is left at this level?”',
    he: 'שולי רווח — מתוך כל 100$ הכנסות, כמה נשאר בכל שלב.',
  });
  SAT.concepts('margins', [
    { id: 'gross-margin', title: 'Gross Margin', short: 'Gross Profit / Revenue — what is left after direct costs.', stmt: 'calc', key: 1,
      what: 'Gross Margin shows how much of a company’s revenue remains after paying the direct costs required to produce its products or services.',
      he: 'מתוך כל 100$ מכירות — כמה נשאר אחרי העלות הישירה?',
      formula: 'Gross Margin = Gross Profit / Revenue',
      example: [['Revenue', '$100'], ['Cost of Revenue', '$40'], ['Gross Profit', '$60'], ['Gross Margin', '60%', 'res']],
      interp: 'For every $100 in revenue, the company retains $60 after direct production/service costs. High gross margin often signals pricing power or a differentiated product.',
      better: ['higher', 'But margins must be compared within the same industry.'],
      compare: ['Previous years', 'Competitors', 'Industry averages'],
      watch: 'Different industries naturally have very different Gross Margins. A supermarket (~25%) and a software company (~75%) should not be compared directly.',
      where: 'Calculated from the Income Statement.',
      q: { tells: 'Product economics and pricing power.', hl: 'Higher is generally better.', compare: 'Own history, direct competitors.', fool: 'Industry differences, cost classification choices, mix shifts.' },
      calc: { id: 'h-gm', defaults: { rev: '100', gp: '60' }, fields: [{ k: 'rev', label: 'Revenue' }, { k: 'gp', label: 'Gross Profit' }], outputs: [{ id: 'm', label: 'Gross Margin', fmt: 'pct', f: (v) => F.margin(v.gp, v.rev) }] },
      related: ['gross-profit', 'operating-margin'] },
    { id: 'operating-margin', title: 'Operating Margin', aka: ['EBIT margin'], short: 'Operating Income / Revenue — profit from core operations per $ of sales.', stmt: 'calc', key: 1,
      what: 'The share of revenue left as operating profit after <b>all</b> operating costs — direct costs <i>and</i> R&amp;D, sales and administration.',
      formula: 'Operating Margin = Operating Income / Revenue',
      example: [['Revenue', '$100'], ['Operating Income', '$25'], ['Operating Margin', '25%', 'res']],
      interp: '<b>Gross vs Operating margin:</b> gross margin shows product economics; operating margin shows the economics of the whole company. A company can have <b>high gross margin but low or negative operating margin</b> if it invests heavily in R&amp;D, sales or infrastructure.',
      better: ['higher', 'Unless it is depressed deliberately by growth investment.'],
      compare: ['Trend over time (operating leverage?)', 'Competitors', 'Management’s long-term target'],
      watch: '<b>Gross Margin ≠ Operating Margin.</b> One-off charges, capitalised costs, or excluding stock-based compensation (“adjusted”) can flatter it.',
      where: 'Calculated from the Income Statement.',
      q: { tells: 'Profitability of the core business after all operating costs.', hl: 'Generally higher is better.', compare: 'History, peers, margin targets.', fool: 'Growth spending, one-offs, “adjusted” numbers excluding real costs.' },
      calc: { id: 'h-om', defaults: { rev: '100', oi: '25' }, fields: [{ k: 'rev', label: 'Revenue' }, { k: 'oi', label: 'Operating Income' }], outputs: [{ id: 'm', label: 'Operating Margin', fmt: 'pct', f: (v) => F.margin(v.oi, v.rev), tone: pct }] },
      related: ['operating-income', 'operating-leverage', 'gross-margin'] },
    { id: 'operating-leverage', title: 'Operating Leverage', short: 'When revenue grows faster than costs, margins expand.', stmt: 'calc',
      what: 'The effect of fixed costs: when a large part of costs is fixed, revenue growth produces <b>proportionally larger</b> growth in operating income — margins expand. It also works in reverse when revenue falls.',
      example: [['Year 1: Revenue / OpEx+COGS', '$100 / $90 → OI $10 (10%)'], ['Year 2: Revenue +20%, costs +10%', '$120 / $99'], ['Operating Income', '$21 (+110%) → 17.5% margin', 'res']],
      interp: 'Revenue grew 20% but operating income more than doubled. This is why investors tolerate low margins in scaling businesses.',
      better: ['context', 'Great on the way up, painful on the way down.'], compare: ['Revenue growth vs OpEx growth', 'Margin trend'],
      watch: 'Expected operating leverage often fails to appear if the company keeps raising spending.',
      where: 'Observed over several years of income statements.', related: ['operating-margin', 'opex'] },
    { id: 'net-margin', title: 'Net Profit Margin', aka: ['Net Margin'], short: 'Net Income / Revenue — bottom-line profit per $ of sales.', stmt: 'calc', key: 1,
      what: 'The share of revenue that ends up as net income for shareholders.',
      formula: 'Net Margin = Net Income / Revenue',
      example: [['Revenue', '$100'], ['Net Income', '$5'], ['Net Margin', '5%', 'res']],
      interp: 'The company keeps $5 of net profit for every $100 of revenue.',
      better: ['higher'], compare: ['History', 'Peers', 'Operating margin (gap shows interest and taxes)'],
      watch: 'Affected by interest, taxes, one-off gains and losses — less “pure” than operating margin.',
      where: 'Calculated from the Income Statement.',
      q: { tells: 'How much of each sale becomes accounting profit for owners.', hl: 'Higher is generally better.', compare: 'History, peers, operating margin.', fool: 'One-offs, tax benefits, investment gains, high leverage.' },
      calc: { id: 'h-nm', defaults: { rev: '100', ni: '5' }, fields: [{ k: 'rev', label: 'Revenue' }, { k: 'ni', label: 'Net Income' }], outputs: [{ id: 'm', label: 'Net Margin', fmt: 'pct', f: (v) => F.margin(v.ni, v.rev), tone: pct }] },
      related: ['net-income', 'operating-margin'] },
  ]);
})();
