/* Section 8 — Valuation, Section 9 — DCF, Section 10 — Investment Thesis */
(function () {
  'use strict';
  const F = SAT.fin;
  SAT.section({
    id: 'valuation', num: 9, title: 'Valuation',
    intro: 'Multiples compare what the market charges with what the business produces.',
    top: `<div class="card banner"><div class="banner-t">GREAT COMPANY ≠ GREAT INVESTMENT</div>
      <p>A fantastic business can still be a poor investment if you buy it at an excessive valuation. The return you earn depends on the <b>price you pay</b> relative to the cash the business will produce.</p>
      ${SAT.he('חברה מצוינת יכולה להיות השקעה גרועה אם קונים אותה במחיר מופרז.')}</div>`,
  });
  SAT.concepts('valuation', [
    { id: 'market-cap', title: 'Market Capitalization', abbr: 'Market Cap', aka: ['Equity value (market)'], short: 'Share Price × Shares Outstanding.', stmt: 'mkt', key: 1,
      what: 'The market value of the company’s equity — what the stock market currently charges for all of its shares.',
      formula: 'Market Cap = Share Price × Shares Outstanding',
      example: [['Share Price', '$50'], ['Shares Outstanding', '2B'], ['Market Cap', '$100B', 'res']],
      interp: '<b>Share price by itself tells almost nothing</b> about whether a stock is cheap. A $500 stock with 100M shares ($50B) is “smaller” than a $10 stock with 10B shares ($100B).',
      better: ['na'], compare: ['Earnings (P/E), FCF (FCF yield), EBITDA (via EV)', 'Your intrinsic value'],
      watch: '<b>Share Price ≠ Valuation.</b> Use diluted shares.', where: 'Share price (market) × shares (10-K/10-Q cover).',
      calc: { id: 'h-mcap', defaults: { p: '50', s: '2B' }, fields: [{ k: 'p', label: 'Share Price' }, { k: 's', label: 'Shares', u: '#' }], outputs: [{ id: 'm', label: 'Market Cap', f: (v) => F.marketCap(v.p, v.s) }] },
      related: ['enterprise-value', 'pe', 'fcf-yield'] },
    { id: 'pe', title: 'P/E', abbr: 'Price-to-Earnings Ratio', short: 'Market Cap / Net Income — $ paid per $1 of earnings.', stmt: 'calc', key: 1, tags: ['earnings multiple', 'earnings yield'],
      what: 'How many dollars investors pay for each dollar of the company’s annual earnings.',
      formula: 'P/E = Market Cap / Net Income\nP/E = Share Price / EPS',
      example: [['Market Cap', '$20B'], ['Net Income', '$1B'], ['P/E', '20x', 'res']],
      interp: 'P/E 20x means investors currently pay ~$20 for every $1 of annual earnings (earnings yield = 1/20 = 5%). <b>Growth and quality matter:</b> a fast-growing, high-ROIC company deserves a higher P/E because its future earnings will be much larger.',
      better: ['context', 'Lower is cheaper only if earnings quality and growth are equal.'], compare: ['The company’s historical P/E', 'Peers', 'Market average', 'Expected EPS growth'],
      watch: '<b>Low P/E ≠ automatically cheap</b> (declining business, peak-cycle earnings, one-off gains). <b>High P/E ≠ automatically expensive</b> (fast growth, temporarily depressed earnings). Meaningless when earnings are negative.',
      where: 'Calculated: market data + Income Statement.',
      q: { tells: 'What the market pays for current earnings.', hl: 'Lower is cheaper — all else equal (it rarely is).', compare: 'History, peers, growth rate.', fool: 'Cyclical peaks, one-offs, buybacks, accounting earnings vs cash.' },
      calc: { id: 'h-pe', defaults: { m: '20B', ni: '1B' }, fields: [{ k: 'm', label: 'Market Cap' }, { k: 'ni', label: 'Net Income' }], outputs: [{ id: 'p', label: 'P/E', fmt: 'x', f: (v) => SAT.div(v.m, v.ni) }] },
      related: ['eps', 'market-cap', 'growth-vs-valuation'] },
    { id: 'enterprise-value', title: 'Enterprise Value', abbr: 'EV', short: 'Market Cap + Debt − Cash — value of the operating business.', stmt: 'calc', key: 1,
      what: 'An approximation of the value of the whole operating business, independent of how it is financed.',
      he: 'שווי פירמה: שווי העסק התפעולי — כולל החוב, בניכוי המזומן.',
      formula: 'EV = Market Cap + Debt − Cash',
      example: [['Market Cap', '$20B'], ['+ Debt', '$5B'], ['− Cash', '$3B'], ['Enterprise Value', '$22B', 'res']],
      interp: 'Imagine buying the whole company: you pay the market cap, but you also <b>take on its debt</b> (you must repay it → add) and you <b>get its cash</b> (it reduces your real cost → subtract). <b>Market Cap = Equity Value. Enterprise Value = approximate value of the operating enterprise.</b>',
      better: ['na'], compare: ['EBITDA, EBIT, FCF, Revenue (EV multiples)', 'DCF enterprise value'],
      watch: '<b>Market Cap ≠ Enterprise Value.</b> A precise EV also adds preferred stock, minority interests and often leases.',
      where: 'Calculated: market data + Balance Sheet.',
      calc: { id: 'h-ev', defaults: { m: '20B', d: '5B', c: '3B' }, fields: [{ k: 'm', label: 'Market Cap' }, { k: 'd', label: 'Debt' }, { k: 'c', label: 'Cash' }], outputs: [{ id: 'e', label: 'Enterprise Value', f: (v) => F.ev(v.m, v.d, v.c) }] },
      related: ['market-cap', 'ev-ebitda', 'dcf-ev'] },
    { id: 'ev-ebitda', title: 'EV / EBITDA', short: 'Enterprise Value / EBITDA — capital-structure-neutral multiple.', stmt: 'calc', key: 1,
      what: 'Values the whole business relative to its EBITDA.',
      formula: 'EV / EBITDA = Enterprise Value / EBITDA',
      example: [['EV', '$20B'], ['EBITDA', '$2B'], ['EV / EBITDA', '10x', 'res']],
      interp: '<b>Why pair EV with EBITDA?</b> EBITDA is earned before interest, so it belongs to <i>all</i> capital providers (debt and equity) — matching EV, which also includes debt. Useful for comparing companies with different leverage and in M&amp;A.',
      better: ['context', 'Lower is cheaper, all else equal.'], compare: ['Peers in the same industry', 'History'],
      watch: '<b>Limitations:</b> EBITDA ignores CapEx, so capital-intensive businesses look cheap. Cross-check with EV/EBIT or Price/FCF. “Adjusted EBITDA” may exclude real costs.',
      where: 'Calculated.',
      q: { tells: 'Price of the whole business per $ of operating earnings before D&A.', hl: 'Lower = cheaper (same industry).', compare: 'Same-industry peers, history.', fool: 'High CapEx needs, adjusted EBITDA, cyclical peaks.' },
      related: ['enterprise-value', 'ebitda'] },
    { id: 'price-fcf', title: 'Price / FCF', aka: ['P/FCF'], short: 'Market Cap / Free Cash Flow.', stmt: 'calc',
      what: 'How many dollars investors pay for each dollar of annual free cash flow.',
      formula: 'Price / FCF = Market Cap / Free Cash Flow',
      example: [['Market Cap', '$10B'], ['FCF', '$0.5B'], ['Price / FCF', '20x', 'res']],
      interp: 'Like P/E but based on cash rather than accounting profit. 20x means paying $20 for $1 of annual FCF.',
      better: ['context', 'Lower is cheaper, all else equal.'], compare: ['P/E', 'History', 'Peers'],
      watch: 'One year of FCF can be lumpy (CapEx timing, working capital). SBC isn’t deducted.', where: 'Calculated.', related: ['fcf-yield', 'fcf'] },
    { id: 'fcf-yield', title: 'FCF Yield', short: 'FCF / Market Cap — cash generated per $100 of market value.', stmt: 'calc', key: 1,
      what: 'Annual free cash flow as a percentage of market value — the cash “yield” you get at today’s price.',
      formula: 'FCF Yield = Free Cash Flow / Market Cap',
      example: [['Market Cap', '$10B'], ['FCF', '$1B'], ['FCF Yield', '10%', 'res']],
      interp: 'For every $100 of market value the company generates ~$10 of FCF per year. <b>Inverse of Price/FCF:</b> 10% yield ⇔ 10x P/FCF; 4% ⇔ 25x.',
      better: ['higher', 'Higher may indicate a cheaper valuation — but growth must be considered.'], compare: ['Bond yields', 'Other stocks', 'Expected FCF growth'],
      watch: 'A high yield with shrinking FCF is a trap; a low yield can be fine with strong growth.', where: 'Calculated.',
      q: { tells: 'Cash return at today’s price, before growth.', hl: 'Higher = cheaper, all else equal.', compare: 'Bond yields, peers, FCF growth.', fool: 'Declining FCF, one-off FCF spikes, ignoring SBC.' },
      calc: { id: 'h-fy', defaults: { f: '1B', m: '10B' }, fields: [{ k: 'f', label: 'FCF' }, { k: 'm', label: 'Market Cap' }], outputs: [{ id: 'y', label: 'FCF Yield', fmt: 'pct', f: (v) => SAT.div(v.f, v.m) }, { id: 'p', label: 'Price / FCF', fmt: 'x', f: (v) => SAT.div(v.m, v.f) }] },
      related: ['price-fcf', 'growth-vs-valuation', 'fcf'] },
    { id: 'growth-vs-valuation', title: 'Growth vs Valuation', short: 'Cheap-today vs bigger-tomorrow tradeoff.', stmt: 'calc', key: 1,
      what: 'The central tradeoff of stock valuation: a stock that gives a lot of cash relative to its price today vs one that gives little today but may grow much larger.',
      body: `<table class="t"><thead><tr><th></th><th>FCF Yield</th><th>FCF Growth</th><th>FCF per $100 — year 0</th><th>Year 5</th><th>Year 10</th></tr></thead><tbody>
        <tr><td class="lbl"><b>Company A</b></td><td>10%</td><td>3%</td><td>$10.00</td><td>$11.59</td><td>$13.44</td></tr>
        <tr><td class="lbl"><b>Company B</b></td><td>4%</td><td>25%</td><td>$4.00</td><td>$12.21</td><td>$37.25</td></tr></tbody></table>`,
      interp: '<b>A</b> provides much more cash relative to today’s valuation. <b>B</b> provides less current cash but potentially much higher future cash — <i>if</i> growth continues. B overtakes A in year 5. Neither metric (yield or growth) should be viewed alone; a DCF combines both.',
      better: ['na'], compare: ['Confidence in B’s growth', 'Durability of A’s cash flows'],
      watch: 'High expected growth is already priced in; if it disappoints, the low-yield stock can fall a lot.', where: '', related: ['fcf-yield', 'dcf-intro'] },
  ]);

  /* ---------- DCF ---------- */
  const STEPS = [['Revenue Forecast', 'Project sales for 5–10 years from growth drivers.'], ['Margin Forecast', 'Project operating / FCF margins.'], ['FCF Forecast', 'Revenue × FCF margin = FCF each year.'],
    ['Discount FCF', 'PV = FCFₜ / (1+r)ᵗ for each year.'], ['Terminal Value', 'Value of all cash after the forecast.'], ['Enterprise Value', 'Sum of PV of FCF + PV of TV.'],
    ['Equity Value', 'EV − Debt + Cash.'], ['Fair Value Per Share', 'Equity Value / Diluted Shares.']];
  SAT.section({
    id: 'dcf', num: 10, title: 'Discounted Cash Flow — DCF',
    intro: '<b>A company is worth the present value of the cash it can generate for its owners in the future.</b> Because future money is worth less than money today, future cash flows are discounted back to today.',
    he: 'חברה שווה את הערך הנוכחי של כל המזומנים שתייצר בעתיד.',
    top: `<div class="card"><h4 style="margin-top:0">The DCF process</h4><div class="proc">${STEPS.map((s, i) => `${i ? '<div class="proc-a">→</div>' : ''}<div class="proc-s"><b>${i + 1}. ${s[0]}</b><span>${s[1]}</span></div>`).join('')}</div>
      <div class="btns"><a class="btn ghost" href="#tool-dcf">Open DCF calculator (tool)</a><a class="btn ghost" href="#tool-sensitivity">Sensitivity table (tool)</a></div></div>`,
  });
  SAT.concepts('dcf', [
    { id: 'dcf-intro', title: 'DCF', abbr: 'Discounted Cash Flow', short: 'Intrinsic value = present value of future free cash flows.', stmt: 'model', key: 1, tags: ['intrinsic value'],
      what: 'A valuation method that estimates what a business is worth today by forecasting its future free cash flows and discounting them back to the present.',
      formula: 'Value = Σ FCFₜ / (1 + r)ᵗ  +  Terminal Value / (1 + r)ᴺ',
      interp: 'The output is only as good as the assumptions. Use it to understand <b>what you must believe</b> for the stock to be cheap — and what the current price implies.',
      better: ['na'], compare: ['Current price (upside/downside)', 'Multiples-based valuation', 'Bear/Base/Bull range'],
      watch: '<b>DCF is based on assumptions, not certainty.</b> Small changes in growth, r or g move the value a lot.', where: 'Built by you.', related: ['present-value', 'terminal-value', 'sensitivity', 'fcff', 'fcfe', 'reverse-dcf'] },
    { id: 'present-value', title: 'Present Value', abbr: 'PV', short: 'Future Cash Flow / (1 + r)^t.', stmt: 'model', key: 1, tags: ['time value of money'],
      what: 'What a future amount of money is worth today. Money today is worth more than money later because it can be invested, and the future is uncertain.',
      formula: 'PV = Future Cash Flow / (1 + r)ᵗ\n\nPV = Present Value · r = Discount Rate · t = Years',
      example: [['$100 received in one year', ''], ['Discount Rate', '10%'], ['PV = 100 / 1.10', '$90.91', 'res']],
      interp: 'At a 10% required return, receiving $90.91 today is equivalent to $100 in a year.',
      better: ['na'], compare: [],
      watch: 'The further away the cash flow and the higher r, the less it is worth today.', where: 'Your model.',
      calc: { id: 'h-pv', defaults: { cf: '100', r: '10', t: '1' }, fields: [{ k: 'cf', label: 'Future cash flow' }, { k: 'r', label: 'Discount rate', u: '%', kind: 'assume' }, { k: 't', label: 'Years', u: 'yrs', kind: 'assume' }], outputs: [{ id: 'p', label: 'Present Value', fmt: 'price', f: (v) => F.pv(v.cf, v.r, v.t) }] },
      related: ['discount-rate', 'dcf-intro'] },
    { id: 'discount-rate', title: 'Discount Rate', abbr: 'r', aka: ['Required return', 'Hurdle rate'], short: 'The rate matched to the cash flows being valued.', stmt: 'model', key: 1,
      what: 'The annual rate used to convert future cash into today’s value. It reflects the time value of money and risk — riskier businesses get higher discount rates. Use WACC for FCFF and the cost of equity for FCFE.',
      example: [['Stable large company', '~7–9%'], ['Average company', '~9–11%'], ['Risky / early-stage', '12%+']],
      interp: 'Discount Rate ↑ → Valuation ↓. Discount Rate ↓ → Valuation ↑.',
      better: ['na'], compare: ['WACC estimates', 'Your own required return'],
      watch: 'A 1-point change in r can move a DCF value by 15–25%.', where: 'Your assumption.', related: ['wacc', 'present-value', 'sensitivity'] },
    { id: 'terminal-value', title: 'Terminal Value', abbr: 'TV', aka: ['Terminal growth', 'Perpetuity value'], short: 'FCF next year / (r − g): value of all cash after the forecast.', stmt: 'model', key: 1, tags: ['terminal growth', 'gordon growth', 'perpetual growth'],
      what: 'We cannot forecast a company year by year forever, so after the explicit forecast (e.g. 10 years) we assume FCF grows at a modest constant rate <b>g</b> forever and capture all of it in one number.',
      formula: 'Terminal Value = FCF next year / (r − g)\n\nr = Discount Rate · g = Terminal Growth Rate\nPV of TV = TV / (1 + r)ᴺ',
      example: [['FCF in final year (N)', '$100'], ['g', '3%'], ['FCF next year', '$103'], ['r', '10%'], ['TV = 103 / 0.07', '$1,471', 'res']],
      interp: 'Terminal value often represents <b>60–80%</b> of a DCF’s total value, because it covers every year after the forecast — that is why DCFs are so sensitive to r and g.',
      better: ['na'], compare: ['Implied exit multiple (TV / final-year EBITDA)'],
      watch: '<b>r must be greater than g</b> — otherwise the formula breaks (division by zero or a negative number). g should not exceed long-run economic growth (~2–4%).',
      where: 'Your model.', related: ['dcf-ev', 'sensitivity', 'discount-rate'] },
    { id: 'dcf-ev', title: 'DCF Enterprise Value', short: 'PV of forecast FCF + PV of terminal value.', stmt: 'model',
      what: 'The value of the whole operating business implied by your DCF.',
      formula: 'Enterprise Value = PV of Forecast FCF + PV of Terminal Value',
      example: [['PV of forecast FCF', '$4B'], ['PV of terminal value', '$11B'], ['Enterprise Value', '$15B', 'res']],
      interp: 'Discount FCFF, the cash flow available to all capital providers, at WACC to estimate operating enterprise value. Discounting FCFE at the cost of equity instead gives equity value.',
      better: ['na'], compare: ['Market EV'], watch: 'Check what share comes from terminal value.', where: 'Your model.', related: ['equity-value', 'enterprise-value', 'fcff', 'fcfe'] },
    { id: 'equity-value', title: 'Equity Value', short: 'Enterprise Value − Debt + Cash.', stmt: 'model', key: 1,
      what: 'The part of enterprise value that belongs to shareholders, after lenders are repaid and cash is added.',
      formula: 'Equity Value = Enterprise Value − Debt + Cash',
      example: [['Enterprise Value', '$15B'], ['− Debt', '$3B'], ['+ Cash', '$1B'], ['Equity Value', '$13B', 'res']],
      interp: 'Comparable to Market Cap. If your equity value is above the market cap, the stock may be undervalued (according to your assumptions).',
      better: ['na'], compare: ['Market Cap'], watch: 'Include all debt-like items (leases, preferred stock, minority interests) for precision.', where: 'Your model.', related: ['fair-value-per-share', 'market-cap'] },
    { id: 'fair-value-per-share', title: 'Fair Value Per Share', aka: ['Intrinsic value per share', 'Target price'], short: 'Equity Value / Diluted Shares.', stmt: 'model', key: 1, tags: ['upside', 'downside'],
      what: 'Your estimate of what one share is worth.',
      formula: 'Fair Value Per Share = Equity Value / Diluted Shares Outstanding\nUpside / Downside = Fair Value / Current Price − 1',
      example: [['Equity Value', '$13B'], ['Diluted Shares', '500M'], ['Fair Value / Share', '$26.00', 'res'], ['Current Price', '$20'], ['Upside', '+30%', 'res']],
      interp: 'Compare with the current price — but as a <b>range</b> (bear/base/bull), not one number.',
      better: ['na'], compare: ['Current share price', 'Bear/base/bull range'], watch: 'Use diluted shares; false precision ($26.37) is a warning sign.', where: 'Your model.', related: ['sensitivity', 'diluted-shares'] },
    { id: 'sensitivity', title: 'Sensitivity Analysis', aka: ['Bear / Base / Bull', 'Scenarios'], short: 'How fair value changes as key assumptions change.', stmt: 'model', key: 1, tags: ['bear', 'base', 'bull', 'scenario'],
      what: 'Re-running the DCF across a grid of assumptions (typically discount rate × terminal growth) to see a <b>range</b> of values instead of one magical number.',
      body: `<div class="arrows"><div><b>Discount Rate ↑</b> → Valuation ↓</div><div><b>Discount Rate ↓</b> → Valuation ↑</div><div><b>Terminal Growth ↑</b> → Valuation ↑</div><div><b>Terminal Growth ↓</b> → Valuation ↓</div></div>
        <div class="three" style="margin-top:10px"><div><h5>Bear case</h5><p>Lower growth, lower margins, higher discount rate, conservative terminal assumptions.</p></div><div><h5>Base case</h5><p>Most reasonable assumptions.</p></div><div><h5>Bull case</h5><p>Higher growth, higher margins, operating leverage.</p></div></div>`,
      interp: 'A good investment often has limited downside in the bear case and meaningful upside in base/bull. Also ask in reverse: <b>what assumptions are already priced into the stock?</b>',
      better: ['na'], compare: ['Current price vs the range'],
      watch: '<b>Valuation should be a range, not a single magical number.</b>', where: 'Your model.', related: ['terminal-value', 'discount-rate'] },
  ]);

  /* ---------- Thesis ---------- */
  const FW = ['Business', 'Moat', 'Growth Drivers', 'Financial Quality', 'Capital Efficiency', 'Valuation', 'Catalysts', 'Risks', 'Bear Case', 'Base Case', 'Bull Case', 'Thesis Invalidation'];
  SAT.section({
    id: 'thesis', num: 11, title: 'Investment Thesis',
    intro: 'A short written argument for why a stock is mispriced and what will make the market see it.',
    top: `<div class="card banner red"><div class="banner-t">WHAT WOULD PROVE ME WRONG?</div>
      <p><b>Confirmation bias</b> is the tendency to seek and believe information that supports what we already think. Once you own a stock, every piece of news starts to look like support. The defence: <b>define thesis-breaking conditions before investing</b>, in writing, with numbers — then act on them when they happen.</p>
      ${SAT.he('מה יוכיח שטעיתי? להגדיר מראש, בכתב, לפני הקנייה.')}
      <p class="muted">Examples: revenue growth falls below X% · margins fall below X% · major customer lost · competitor gains significant share · debt rises above X · product launch fails · regulatory change.</p>
      <div class="btns"><a class="btn" href="#tool-thesis">Open thesis worksheet (tool)</a></div></div>`,
  });
  SAT.concepts('thesis', [
    { id: 'thesis-def', title: 'Investment Thesis', short: 'Why the stock is mispriced, why it will change, and what would prove you wrong.', stmt: 'qual', key: 1,
      what: 'A concise argument (a few sentences) explaining <b>what you believe that the market doesn’t</b>, why it matters for value, and what will make the market recognise it.',
      body: `<div class="fwk">${FW.map((x, i) => `<div><span>${i + 1}</span>${x}</div>`).join('')}</div>`,
      interp: 'A good thesis is specific and falsifiable: “Margins will expand from 10% to 18% as data-centre utilisation rises; the market prices in 12%.”',
      better: ['na'], compare: ['What the current price implies'],
      watch: '“Great company” is not a thesis. If you can’t say why the market is wrong, you probably don’t have an edge.', where: 'Your notes.', related: ['invalidation', 'catalysts', 'risk-factors'] },
    { id: 'invalidation', title: 'Thesis Invalidation', short: 'Pre-defined conditions that would prove the thesis wrong.', stmt: 'qual', key: 1, tags: ['prove me wrong', 'confirmation bias'],
      what: '3–10 specific, measurable conditions — written before you invest — that would mean your thesis is broken.',
      example: [['Revenue growth', '< 10% for two quarters'], ['Operating margin', '< 15%'], ['Net debt / EBITDA', '> 3x'], ['Key customer', 'Lost']],
      interp: 'When a condition triggers, re-underwrite from scratch: would you buy this stock today at this price?',
      better: ['na'], compare: ['Actual results each quarter'],
      watch: 'Moving the goalposts after the fact (“it’s only temporary”) is confirmation bias in action.', where: 'Your notes.', related: ['thesis-def'] },
  ]);
})();
